Repository Runvengers/Running-Mate-Front, pull requests merged in 2021-11, with the labels that each got.

#6 add address
  frontend/.pnp.cjs
  frontend/.yarn/cache/async-npm-0.9.2-d8cafe6cc3-87dbf12929.zip
  frontend/.yarn/cache/ejs-npm-3.1.6-03db39fd15-81a9cdea0b.zip
  frontend/.yarn/cache/filelist-npm-1.0.2-d98495ab20-4d6953cb6f.zip
  frontend/.yarn/cache/jake-npm-10.8.2-e211473cb9-b604c51863.zip
  frontend/.yarn/cache/react-daum-postcode-npm-3.0.0-5397f1a703-cae14f6f22.zip
  frontend/package.json
  frontend/src/Home/Home.tsx
  frontend/src/adress/Adress.tsx
  frontend/yarn.lock
Labels: 기능구현

#14 [민수] 로그인 기능 구현
  frontend/.eslintrc
  frontend/.pnp.cjs
  frontend/.yarn/cache/@testing-library-dom-npm-8.11.1-d1ef937c19-082104b104.zip
  frontend/.yarn/cache/aria-query-npm-5.0.0-986fb11e0e-c41f98866c.zip
  frontend/.yarn/cache/dom-accessibility-api-npm-0.5.10-74ce83a819-c05949889b.zip
  frontend/.yarn/cache/eslint-config-airbnb-base-npm-15.0.0-802837dd26-38626bad2c.zip
  frontend/.yarn/cache/eslint-config-airbnb-typescript-npm-16.0.0-61f328b252-8bc5f0c93b.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/components/SignIn/SignInModal.test.tsx
  frontend/src/__tests__/modules/signIn.test.ts
  frontend/src/components/Home/Home.tsx
  frontend/src/components/Modals/SignAndUpModal.module.css
  frontend/src/components/Modals/SignInModal.tsx
  frontend/src/components/Modals/SignUpModal.module.css
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/modules/index.ts
  frontend/src/modules/saga/signInSaga.ts
  frontend/src/modules/saga/signUpSaga.ts
  frontend/src/modules/signIn.ts
  frontend/src/modules/signUp.ts
  frontend/src/modules/types/signInTypes.d.ts
  frontend/src/modules/types/signUpTypes.d.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 버그, 기능구현, 테스팅

#19 [민수, 석훈] Cypress로 로그인 e2e테스트 구현
  frontend/cypress/integration/SignInAndUp/signIn.test.ts
  frontend/src/components/GuestPage/GuestPage.tsx
  frontend/src/components/Modals/SignInModal.tsx
  frontend/src/components/Modals/SignUpModal.tsx
  frontend/tsconfig.json
Labels: 테스팅
