Repository Runvengers/Running-Mate-Front, pull requests merged in 2021-12, with the labels that each got.

#22 [석훈] Home(게시판) navigation 컴포넌트 구현
  frontend/src/common/colors.css
  frontend/src/components/Home/Home.module.css
  frontend/src/components/Home/Home.tsx
Labels: 기능구현

#25 [민수] 공통 헤더 제작 (디자인)
  frontend/.pnp.cjs
  frontend/.yarn/cache/@types-react-outside-click-handler-npm-1.3.0-1f698df67f-41fa8f8482.zip
  frontend/.yarn/cache/airbnb-prop-types-npm-2.16.0-d794f5271c-393a5988b9.zip
  frontend/.yarn/cache/array.prototype.find-npm-2.1.2-d476d9472a-fd3f56a9e0.zip
  frontend/.yarn/cache/consolidated-events-npm-2.0.2-4a127006c6-3ffb9fa264.zip
  frontend/.yarn/cache/document.contains-npm-1.0.2-b186799607-dbb8c1f6ec.zip
  frontend/.yarn/cache/function.prototype.name-npm-1.1.5-e776a642bb-acd21d733a.zip
  frontend/.yarn/cache/functions-have-names-npm-1.2.2-c348c7c2a0-25f44b6d1c.zip
  frontend/.yarn/cache/prop-types-exact-npm-1.2.0-4664209648-21676a16d5.zip
  frontend/.yarn/cache/react-outside-click-handler-npm-1.3.0-7fa0d196a3-c3afc3ce1c.zip
  frontend/.yarn/cache/reflect.ownkeys-npm-0.2.0-e3d8f6e4f0-9530b16656.zip
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/UserProfile.tsx
  frontend/src/index.css
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: 디자인

#26 [기능] 게시판 컴포넌트 완성
  frontend/src/__tests__/common/functions/remainDateParser.test.ts
  frontend/src/common/functions/remainDateParser.ts
  frontend/src/components/Board/Board.tsx
  frontend/src/components/Board/RemainDate.tsx
  frontend/src/components/Home/Home.module.css
  frontend/src/components/Home/Home.tsx
  frontend/src/excuteData/BoardMock/BoardMock.ts
  frontend/src/hooks/useDidMount.tsx
Labels: 기능구현, 디자인

#30 [민수] 컴포넌트 테스팅 오류 해결
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/components/SignIn/SignInModal.test.tsx
  frontend/src/components/Modals/SignInModal.tsx
Labels: 버그, 기능수정

#32 [민수] 크루 메인페이지 제작
  frontend/.pnp.cjs
  frontend/.yarn/cache/@types-lodash-npm-4.14.177-a28410b30a-00f9eb300e.zip
  frontend/.yarn/cache/@types-testing-library__jest-dom-npm-5.14.2-639cce59b8-e08715a565.zip
  frontend/.yarn/cache/history-npm-5.1.0-312a8162fd-c978710a18.zip
  frontend/cypress/integration/Crew/Crew.test.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/components/Crew/Crew.test.tsx
  frontend/src/components/Crew/Crew.tsx
  frontend/src/components/Crew/CrewDetail.tsx
  frontend/src/excuteData/CrewMock/CrewMock.ts
  frontend/src/lib/URL/Image.ts
  frontend/src/modules/saga/signInSaga.ts
  frontend/src/modules/signIn.ts
  frontend/src/modules/types/signInTypes.d.ts
  frontend/yarn.lock
Labels: 기능구현, 테스팅

#31 [석훈] Home navigation 컴포넌트 최적화
  frontend/src/components/Home/Home.tsx
Labels: 리펙토링

#35 [민수] 비밀번호 변경 컴포넌트 제작 완료
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/components/Crew/Crew.test.tsx
  frontend/src/__tests__/components/Mypage/ChangeMyPassword.test.tsx
  frontend/src/__tests__/modules/newPassword.test.ts
  frontend/src/components/Mypage/ChangeMyPassword.tsx
  frontend/src/components/Mypage/MyPage.tsx
  frontend/src/components/Mypage/MyPageMenu.tsx
  frontend/src/modules/index.ts
  frontend/src/modules/newPassword.ts
  frontend/src/modules/types/newPassword.d.ts
Labels: 기능구현, 테스팅, 디자인

#34 Seokunee/issue27
  frontend/cypress/integration/CreateCrew/CreateCrew.test.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/components/CreateCrew/CreateCrew.test.tsx
  frontend/src/components/CreateCrew/CreateCrew.tsx
  frontend/src/components/CreateCrew/CreateCrewOrderMarker.tsx
  frontend/src/modules/createCrew.ts
  frontend/src/modules/index.ts
Labels: 기능구현, 테스팅, 디자인

#38 [석훈] issue merge 과정에서 생긴 mockStore 오류 수정
  frontend/src/__mocks__/reduxMock/storeMock.ts
Labels: 기능수정

#39 Seokunee/issue36
  frontend/src/components/FindUser/FindUser.module.css
  frontend/src/components/FindUser/FindUser.tsx
  frontend/src/excuteData/UsersMock/UsersMock.ts
Labels: 기능구현, 디자인
