Repository Runvengers/Running-Mate-Front, pull requests merged in 2022-01, with the labels that each got.

#50 [민수] 크루 정보수정 페이지 제작
  frontend/src/App.tsx
  frontend/src/__tests__/components/CreateCrew/CreateCrew.test.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrew.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrewOrderMarker.tsx
  frontend/src/components/Crew/CrewDetail/CrewDetail.tsx
  frontend/src/components/Crew/CrewDetail/CrewWidget.tsx
  frontend/src/components/Crew/CrewManagement/CrewManagement.tsx
  frontend/src/components/Crew/CrewManagement/CrewManagementMenu.tsx
  frontend/src/components/Crew/CrewManagement/Management.tsx
  frontend/src/components/Crew/CrewManagement/PeopleList.tsx
  frontend/src/components/Crew/CrewManagement/PeopleManagement.tsx
  frontend/src/components/Modals/SignInModal.tsx
  frontend/src/components/Modals/SignUpModal.tsx
  frontend/src/components/Mypage/ChangeMyPassword.tsx
  frontend/src/components/Mypage/MyPageInformations.tsx
  frontend/src/hooks/usePasswordCheck.tsx
  frontend/tailwind.config.js
Labels: 디자인, 기능수정

#52 [석훈] 공지(Notice) 생성 컴포넌트 제작
  frontend/.pnp.cjs
  frontend/.yarn/cache/@popperjs-core-npm-2.11.0-13e8017699-84d6f197d3.zip
  frontend/.yarn/cache/@types-quill-npm-1.3.10-4ddf84ba7e-e629157d11.zip
  frontend/.yarn/cache/@types-react-datepicker-npm-4.3.4-0f5827b98a-1107b09fee.zip
  frontend/.yarn/cache/classnames-npm-2.3.1-f2ae0a8d3c-14db8889d5.zip
  frontend/.yarn/cache/clone-npm-2.1.2-1d491c6629-aaf106e9bc.zip
  frontend/.yarn/cache/create-react-class-npm-15.7.0-667818a95c-0c5f43da70.zip
  frontend/.yarn/cache/date-fns-npm-2.28.0-c19c5add1b-a0516b2e4f.zip
  frontend/.yarn/cache/eventemitter3-npm-2.0.3-71d4ac3a65-dfbf4a0714.zip
  frontend/.yarn/cache/fast-diff-npm-1.1.2-907d4b29ef-2ef726603e.zip
  frontend/.yarn/cache/parchment-npm-1.1.4-a3bac35728-4799756742.zip
  frontend/.yarn/cache/prop-types-npm-15.8.0-6f60fc44c7-d8d51cf55d.zip
  frontend/.yarn/cache/quill-delta-npm-3.6.3-3ae240a64d-e62ed33983.zip
  frontend/.yarn/cache/quill-npm-1.3.7-c79f7446fc-db3e265a84.zip
  frontend/.yarn/cache/react-datepicker-npm-4.5.0-d6f7d61e3d-a1e8107079.zip
  frontend/.yarn/cache/react-dom-factories-npm-1.0.2-6ae7e7abb2-2ef14d4bb1.zip
  frontend/.yarn/cache/react-fast-compare-npm-3.2.0-fbfa6627d9-8ef272c825.zip
  frontend/.yarn/cache/react-onclickoutside-npm-6.12.1-72fd42cce1-aae4c1c2e7.zip
  frontend/.yarn/cache/react-popper-npm-2.2.5-6e86e4bf1e-915fcf08e1.zip
  frontend/.yarn/cache/react-quill-npm-1.3.5-7e94f3f824-c0bfa816c2.zip
  frontend/.yarn/cache/warning-npm-4.0.3-291e921d6d-4f2cb6a957.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/modules/createNotice.test.ts
  frontend/src/components/CreateNotice/CreateNotice.tsx
  frontend/src/components/Home/Home.tsx
  frontend/src/index.css
  frontend/src/modules/createNotice.ts
  frontend/src/modules/index.ts
  frontend/src/modules/types/createNotice.d.ts
  frontend/yarn.lock
Labels: 기능구현, 테스팅, 디자인

#53 [석훈, 민수] 회원가입, 로그인 백엔드 API와 연동하여 기능 완성해내기.
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/modules/HEADER_TEST.test.ts
  frontend/src/__tests__/modules/JOIN_TEST.test.ts
  frontend/src/__tests__/modules/LOGIN_TEST.test.ts
  frontend/src/components/CreateNotice/CreateNotice.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrew.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrewOrderMarker.tsx
  frontend/src/components/Crew/Crew.tsx
  frontend/src/components/Crew/CrewDetail/CrewDetail.tsx
  frontend/src/components/FindUser/FindUser.tsx
  frontend/src/components/Home/Home.tsx
  frontend/src/components/Modals/SignInModal.tsx
  frontend/src/components/Modals/SignUpModal.tsx
  frontend/src/components/Mypage/ChangeMyPassword.tsx
  frontend/src/components/Mypage/MyPageInformations.tsx
  frontend/src/components/Mypage/MyPageMenu.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
  frontend/src/hooks/useDidMount.tsx
  frontend/src/lib/api/axios.ts
  frontend/src/modules/saga/signInSaga.ts
  frontend/src/modules/saga/signUpSaga.ts
  frontend/src/modules/signIn.ts
  frontend/src/modules/signUp.ts
  frontend/src/modules/types/signInTypes.d.ts
  frontend/src/modules/types/signUpTypes.d.ts
Labels: 기능구현, 기능수정

#61 [석훈, 민수] 반응형 70% 구현 #58
  frontend/src/common/components/DetailBaseBorder.tsx
  frontend/src/common/components/MenuButton.tsx
  frontend/src/common/components/NextPageButton.tsx
  frontend/src/common/components/PreviousPageButton.tsx
  frontend/src/components/Board/Board.tsx
  frontend/src/components/CreateNotice/CreateNotice.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrew.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrewOrderMarker.tsx
  frontend/src/components/Crew/Crew.tsx
  frontend/src/components/Crew/CrewDetail/CrewDetail.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/UserProfile.tsx
  frontend/src/components/Home/Home.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
Labels: 디자인

#66 issue #65
  frontend/.pnp.cjs
  frontend/.yarn/cache/eslint-module-utils-npm-2.7.2-eb43175cc1-3e6407461d.zip
  frontend/.yarn/cache/eslint-plugin-import-npm-2.25.4-cd0cf8b05b-0af24f5c7c.zip
  frontend/.yarn/cache/is-core-module-npm-2.8.1-ce21740d1b-418b7bc107.zip
  frontend/.yarn/cache/tsconfig-paths-npm-3.12.0-b78aadfb3f-4999ec6cd1.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/components/Crew/Crew.tsx
  frontend/src/components/Crew/CrewDetail/CrewWidget.tsx
  frontend/src/components/Header/UserProfile.tsx
  frontend/src/components/Modals/SignUpModal.tsx
  frontend/src/components/Mypage/MyPage.tsx
  frontend/src/components/Mypage/MyPageInformations.tsx
  frontend/src/components/Mypage/MyPageMenu.tsx
  frontend/src/components/UserPage/Userpage.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
  frontend/src/excuteData/UserPageMock/UserPageMock.ts
  frontend/src/lib/api/userService.ts
  frontend/src/modules/createNotice.ts
  frontend/src/modules/saga/signInSaga.ts
  frontend/src/modules/saga/signUpSaga.ts
  frontend/src/modules/signIn.ts
  frontend/src/modules/types/createNotice.d.ts
  frontend/src/modules/types/signInTypes.d.ts
  frontend/src/modules/types/signUpTypes.d.ts
  frontend/yarn.lock
Labels: 기능구현, 디자인, 기능수정, 리펙토링

#67 [민수] 회원전용 페이지 유무를 위한 hook생성
  frontend/src/App.tsx
  frontend/src/components/Mypage/LeaveAccount.tsx
  frontend/src/components/Mypage/MyPage.tsx
  frontend/src/components/Mypage/MyPageMenu.tsx
  frontend/src/hooks/useRequireLogin.tsx
Labels: 기능구현, 기능수정, 리펙토링

#71 [석훈] 게시판 생성 API적용
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/components/CreateNotice/CreateNotice.tsx
  frontend/src/components/SelectRegion/SelcetRegion.tsx
  frontend/src/lib/api/notiveService.ts
  frontend/src/lib/data/regions.ts
  frontend/src/modules/createNotice.ts
  frontend/src/modules/types/createNotice.d.ts
Labels: 기능구현, 디자인, 기능수정, 리펙토링

#70 [민수] 유저 페이지 별 정보 조회완료
  frontend/src/App.tsx
  frontend/src/components/Board/Board.tsx
  frontend/src/components/Crew/CrewDetail/CrewWidget.tsx
  frontend/src/components/FindUser/FindUser.tsx
  frontend/src/components/Header/UserProfile.tsx
  frontend/src/components/Mypage/LeaveAccount.tsx
  frontend/src/components/Mypage/MyPageInformations.tsx
  frontend/src/components/Mypage/MyPageMenu.tsx
  frontend/src/components/UserPage/Userpage.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
  frontend/src/hooks/useLocalStorageData.tsx
  frontend/src/lib/api/userService.ts
Labels: 기능구현, 디자인, 기능수정

#75 [민수] 크루 생성하기, 조회 API연동
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/__tests__/modules/crew.test.ts
  frontend/src/common/components/NextPageButton.tsx
  frontend/src/common/components/PreviousPageButton.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrew.tsx
  frontend/src/components/Crew/CreateCrew/CreateCrewOrderMarker.tsx
  frontend/src/components/Crew/Crew.tsx
  frontend/src/components/Crew/CrewDetail/CrewDetail.tsx
  frontend/src/components/Crew/CrewDetail/CrewWidget.tsx
  frontend/src/components/Crew/CrewManagement/CrewManagement.tsx
  frontend/src/components/Crew/CrewManagement/CrewManagementMenu.tsx
  frontend/src/components/Crew/CrewManagement/Management.tsx
  frontend/src/components/Crew/CrewManagement/PeopleManagement.tsx
  frontend/src/components/GuestPage/GuestPage.module.css
  frontend/src/components/GuestPage/GuestPage.tsx
  frontend/src/components/UserPage/Userpage.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
  frontend/src/excuteData/CrewMock/CrewRewardMock.ts
  frontend/src/hooks/useLocalStorageData.tsx
  frontend/src/hooks/useRequireLogin.tsx
  frontend/src/lib/api/crewService.ts
  frontend/src/lib/api/userService.ts
  frontend/src/modules/createCrew.ts
  frontend/src/modules/crew.ts
  frontend/src/modules/index.ts
  frontend/src/modules/saga/createCrewSaga.ts
  frontend/src/modules/saga/index.ts
  frontend/src/modules/types/createCrew.d.ts
  frontend/src/modules/types/crewTypes.d.ts
  frontend/tailwind.config.js
Labels: 기능구현, 테스팅, 디자인, 기능수정

#80 [민수]크루 이름 변경, 크루 리스트 페이징 API 적용
  frontend/.pnp.cjs
  frontend/.yarn/cache/@types-react-router-dom-npm-5.3.1-ac4e931eb2-44621f53c1.zip
  frontend/.yarn/cache/@types-react-router-dom-npm-5.3.2-85c77b2709-90f052dc5a.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/components/Crew/CreateCrew/CreateCrew.tsx
  frontend/src/components/Crew/Crew.tsx
  frontend/src/components/Crew/CrewCard.tsx
  frontend/src/components/Crew/CrewDetail/CrewDetail.tsx
  frontend/src/components/Crew/CrewImageSlider.tsx
  frontend/src/components/Crew/CrewManagement/CrewDelete.tsx
  frontend/src/components/Crew/CrewManagement/CrewManagement.tsx
  frontend/src/components/Crew/CrewManagement/CrewManagementMenu.tsx
  frontend/src/components/Crew/CrewManagement/Management.tsx
  frontend/src/components/Crew/CrewManagement/PeopleList.tsx
  frontend/src/components/Crew/CrewManagement/PeopleManagement.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Mypage/LeaveAccount.tsx
  frontend/src/components/Mypage/MyPage.tsx
  frontend/src/excuteData/CrewMock/CrewMock.ts
  frontend/src/hooks/useLocalStorageData.tsx
  frontend/src/hooks/useRequireLogin.tsx
  frontend/src/hooks/useValidToken.tsx
  frontend/src/lib/api/crewService.ts
  frontend/src/lib/api/userService.ts
  frontend/src/modules/createCrew.ts
  frontend/src/modules/crew.ts
  frontend/src/modules/saga/createCrewSaga.ts
  frontend/src/modules/saga/deleteCrewSaga.ts
  frontend/src/modules/saga/index.ts
  frontend/src/modules/saga/signUpRequestCrewSaga.ts
  frontend/src/modules/types/createCrew.d.ts
  frontend/src/modules/types/crewTypes.d.ts
  frontend/yarn.lock
Labels: 기능구현, 디자인, 기능수정, 변경사항

#81 [석훈] 변경된 url,데이터 적용, Home 무한스크롤 구현
  frontend/.pnp.cjs
  frontend/.yarn/cache/react-intersection-observer-npm-8.33.1-6dc3562a3c-5feb0df01d.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/common/functions/dateParser.ts
  frontend/src/common/functions/findFirstRegion.ts
  frontend/src/components/Board/Board.tsx
  frontend/src/components/Board/CreateNotice/CreateNotice.tsx
  frontend/src/components/Board/EditNotice/EditNotice.tsx
  frontend/src/components/Board/RemainDate.tsx
  frontend/src/components/Board/ViewNotice/ViewNotice.tsx
  frontend/src/components/Home/Home.tsx
  frontend/src/components/SelectRegion/SelcetRegion.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
  frontend/src/excuteData/BoardMock/BoardMock.ts
  frontend/src/lib/api/noticeService.ts
  frontend/src/modules/createNotice.ts
  frontend/src/modules/index.ts
  frontend/src/modules/notice.ts
  frontend/src/modules/types/notice.d.ts
  frontend/yarn.lock
Labels: 기능구현, 기능수정, 리펙토링

#82 #76
  frontend/.pnp.cjs
  frontend/.yarn/cache/react-intersection-observer-npm-8.33.1-6dc3562a3c-5feb0df01d.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mocks__/reduxMock/storeMock.ts
  frontend/src/common/functions/dateParser.ts
  frontend/src/common/functions/findFirstRegion.ts
  frontend/src/components/Board/Board.tsx
  frontend/src/components/Board/CreateNotice/CreateNotice.tsx
  frontend/src/components/Board/EditNotice/EditNotice.tsx
  frontend/src/components/Board/RemainDate.tsx
  frontend/src/components/Board/ViewNotice/ViewNotice.tsx
  frontend/src/components/Home/Home.tsx
  frontend/src/components/SelectRegion/SelcetRegion.tsx
  frontend/src/components/ViewNotice/ViewNotice.tsx
  frontend/src/excuteData/BoardMock/BoardMock.ts
  frontend/src/lib/api/noticeService.ts
  frontend/src/modules/createNotice.ts
  frontend/src/modules/index.ts
  frontend/src/modules/notice.ts
  frontend/src/modules/types/notice.d.ts
  frontend/yarn.lock
Labels: 기능구현, 기능수정, 리펙토링
